---
 - hosts: all
   become: yes
   tasks:

   - name: Upgarde All Packages
     yum:
       name: '*'
       state: latest

   - name: Java RPM package download
     get_url:
       url: https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-linux-x64.rpm
       dest: /tmp

   - name: Install java
     yum:
       name: java
       state: present

   - name: Download Jenkins Repo
     get_url:
       url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo

   - name: Download Key
     rpm_key:
       key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
       state: present

   - name: Install Jenkins
     yum:
       name: jenkins
       state: present

   - name: Start jenkins service
     service:
       name: jenkins
       state: started

   - name: Run command to retrive the default password
     command: cat /var/lib/jenkins/secrets/initialAdminPassword
     register: initialAdminPassword
     ignore_errors: yes

   - name: See the retrived password using debug
     debug:
       var: initialAdminPassword.stdout

   - name: Install Different Packages
     yum:
       name: ['git', 'maven', 'python']
       state: present

   - name: Downloading NGINX .rpm Package
     get_url:
        url: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
        dest: /tmp

   - name: Install Nginx
     yum:
       name: nginx
       state: present

   - name: Sonarqube package download
     get_url:
        url: http://downloads.sourceforge.net/project/sonar-pkg/rpm/sonar.repo
        dest: /etc/yum.repos.d/sonar.repo 

   - name: Install Sonarqube
     yum:
       name: Sonar
       state: present

   - name: Start Sonarqube service
     service:
       name: sonar
       state: started  
